SET REFERENTIAL_INTEGRITY FALSE;

DELETE
FROM MEAL;
DELETE
FROM INGREDIENT;
DELETE
FROM INGREDIENT_MEAL;

INSERT INTO MEAL (meal_id, name)
VALUES (1, 'Spaghetti');
INSERT INTO MEAL (meal_id, name)
VALUES (2, 'Pizza');
INSERT INTO MEAL (meal_id, name)
VALUES (3, 'Beef Steak');
INSERT INTO MEAL (meal_id, name)
VALUES (4, 'Tiramisu');
INSERT INTO MEAL (meal_id, name)
VALUES (5, 'Pancakes');

INSERT INTO INGREDIENT
VALUES (1, 12, 13, 14, 'name', 15);

SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO INGREDIENT_MEAL
VALUES (1, 1);
